name: Sync Fork

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add upstream repo
        run: git remote add upstream https://github.com/OWNER/REPO.git

      - name: Fetch and merge upstream changes
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit || echo "No changes to merge"
          git push origin main
